"""STM32F0xx"""

import swd.targets.stm32 as _stm32


class Stm32l0(_stm32.Stm32):
    """STM32F0xx"""

    _CORE = "Cortex-M0+"
    _FAMILY = "STM32L0"
    _IDCODE_REG = 0x40015800
    _FLAS_SIZE_REG = 0x1ff8007c
    _FREQ = 32000000
    _DEVICES = [
        {
            'part_no': 'STM32L011x3',
            'dev_id': 0x457,
            'flash_size': 8 * _stm32.KILO,
            'sram_size': 2 * _stm32.KILO,
            'eeprom_size': 512,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L011x4',
            'dev_id': 0x457,
            'flash_size': 16 * _stm32.KILO,
            'sram_size': 2 * _stm32.KILO,
            'eeprom_size': 512,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L021x4',
            'dev_id': 0x457,
            'flash_size': 16 * _stm32.KILO,
            'sram_size': 2 * _stm32.KILO,
            'eeprom_size': 512,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L031x4',
            'dev_id': 0x457,
            'flash_size': 16 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 1 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L031x6',
            'dev_id': 0x457,
            'flash_size': 32 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 1 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L041x6',
            'dev_id': 0x457,
            'flash_size': 32 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 1 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L051x6',
            'dev_id': 0x457,
            'flash_size': 32 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 2 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L051x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 2 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L052x6',
            'dev_id': 0x457,
            'flash_size': 32 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 2 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L052x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 2 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L053x6',
            'dev_id': 0x457,
            'flash_size': 32 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 2 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L053x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 2 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L062x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 2 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L063x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 8 * _stm32.KILO,
            'eeprom_size': 2 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L071x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 3 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L071xB',
            'dev_id': 0x457,
            'flash_size': 128 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L071xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L072x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 3 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L072xB',
            'dev_id': 0x457,
            'flash_size': 128 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L072xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L073x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 3 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L073xB',
            'dev_id': 0x457,
            'flash_size': 128 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L073xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L081xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L081xB',
            'dev_id': 0x457,
            'flash_size': 128 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L082xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L082xB',
            'dev_id': 0x457,
            'flash_size': 128 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L083x8',
            'dev_id': 0x457,
            'flash_size': 64 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 3 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L083xB',
            'dev_id': 0x457,
            'flash_size': 128 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, {
            'part_no': 'STM32L083xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _stm32.KILO,
            'sram_size': 20 * _stm32.KILO,
            'eeprom_size': 6 * _stm32.KILO,
            'freq': 32,
            'flash_page_size': 128,
        }, ]

    def __init__(self, cortexm, expected_devices=None):
        super().__init__(cortexm, expected_devices)
