"""STM32F0xx"""

import swd.targets.memory as _mem
import swd.targets.stm32 as _stm32


class Stm32l0(_stm32.Stm32):
    """STM32L0xx"""

    _NAME = "STM32L0"
    _IDCODE_REG = 0x40015800
    _FLAS_SIZE_REG = 0x1ff8007c
    _FREQ = 32000000
    _MCUS = [
        {
            'mcu_name': 'STM32L011x3',
            'dev_id': 0x457,
            'flash_size': 8 * _mem.KILO,
            'sram_size': 2 * _mem.KILO,
            'eeprom_size': 512,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L011x4',
            'dev_id': 0x457,
            'flash_size': 16 * _mem.KILO,
            'sram_size': 2 * _mem.KILO,
            'eeprom_size': 512,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L021x4',
            'dev_id': 0x457,
            'flash_size': 16 * _mem.KILO,
            'sram_size': 2 * _mem.KILO,
            'eeprom_size': 512,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L031x4',
            'dev_id': 0x457,
            'flash_size': 16 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 1 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L031x6',
            'dev_id': 0x457,
            'flash_size': 32 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 1 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L041x6',
            'dev_id': 0x457,
            'flash_size': 32 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 1 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L051x6',
            'dev_id': 0x457,
            'flash_size': 32 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 2 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L051x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 2 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L052x6',
            'dev_id': 0x457,
            'flash_size': 32 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 2 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x2.svd',
        }, {
            'mcu_name': 'STM32L052x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 2 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x2.svd',
        }, {
            'mcu_name': 'STM32L053x6',
            'dev_id': 0x457,
            'flash_size': 32 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 2 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, {
            'mcu_name': 'STM32L053x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 2 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, {
            'mcu_name': 'STM32L062x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 2 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x2.svd',
        }, {
            'mcu_name': 'STM32L063x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 8 * _mem.KILO,
            'eeprom_size': 2 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, {
            'mcu_name': 'STM32L071x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 3 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L071xB',
            'dev_id': 0x457,
            'flash_size': 128 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L071xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L072x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 3 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x2.svd',
        }, {
            'mcu_name': 'STM32L072xB',
            'dev_id': 0x457,
            'flash_size': 128 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x2.svd',
        }, {
            'mcu_name': 'STM32L072xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x2.svd',
        }, {
            'mcu_name': 'STM32L073x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 3 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, {
            'mcu_name': 'STM32L073xB',
            'dev_id': 0x457,
            'flash_size': 128 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, {
            'mcu_name': 'STM32L073xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, {
            'mcu_name': 'STM32L081xB',
            'dev_id': 0x457,
            'flash_size': 128 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L081xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x1.svd',
        }, {
            'mcu_name': 'STM32L082xB',
            'dev_id': 0x457,
            'flash_size': 128 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x2.svd',
        }, {
            'mcu_name': 'STM32L082xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x2.svd',
        }, {
            'mcu_name': 'STM32L083x8',
            'dev_id': 0x457,
            'flash_size': 64 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 3 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, {
            'mcu_name': 'STM32L083xB',
            'dev_id': 0x457,
            'flash_size': 128 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, {
            'mcu_name': 'STM32L083xZ',
            'dev_id': 0x457,
            'flash_size': 192 * _mem.KILO,
            'sram_size': 20 * _mem.KILO,
            'eeprom_size': 6 * _mem.KILO,
            'freq': 32,
            'flash_page_size': 128,
            'svd_file': 'svd/STM32L0_svd_V1.2/STM32L0x3.svd',
        }, ]
